
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liQxMn6aZlPwDmTJ
            client-secret: 1974b2b1ed1e9414bb94cc40bb37b8ce56a834f6
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
